### ISSUE TITLE
Access denied from ghcr.io

### ISSUE THREAD

**Issue by Nikos410** [grantbevis/borg-server#10]
Hey there,

thanks for providing this image! Since the last few days, I cannot pull this image anymore:

```
Pulling borg-server ... error

ERROR: for borg-server  Head "https://ghcr.io/v2/b3vis/borg-server/manifests/latest": denied
ERROR: Head "https://ghcr.io/v2/b3vis/borg-server/manifests/latest": denied
```

Is some kind of authentication required now?

Thanks in advance!

**Comment by Nikos410** [comment]
Ah, nevermind, I just noticed I have to use `grantbevis/` instead of `b3vis` now.

**Comment by grantbevis** [comment]
My bad sorry, I renamed my GitHub account
